blank_issues_enabled: false
contact_links:
  - name: Create Issue on GitLab
    url: https://gitlab.com/Niwla23/schoolbot/-/issues/new
    about: This project is just a mirror. The source code and issues are on GitLab.
